checksumBehavior: update

enableNetwork: true

httpTimeout: 60000

networkConcurrency: 200
nmHoistingLimits: workspaces

nodeLinker: node-modules
ignorePath: true

npmRegistryServer: "http://172.16.32.101:8081/repository/mobile-public"

unsafeHttpWhitelist:
  - 172.16.32.101
